import os
import ast

def generate_matrix():
    # Dynamically find the directory where this script is located
    models_dir = os.path.dirname(os.path.abspath(__file__))
    script_name = os.path.basename(__file__)
    
    matrix = {}
    
    # 1. Scan and parse all valid model files in this directory
    for filename in sorted(os.listdir(models_dir)):
        # Exclude __init__.py and this generator script itself
        if filename.endswith(".py") and filename not in ("__init__.py", script_name):
            file_path = os.path.join(models_dir, filename)
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    tree = ast.parse(f.read())
                
                for node in ast.walk(tree):
                    # Target only classes that follow your canonical naming rule
                    if isinstance(node, ast.ClassDef) and node.name.startswith("Canonical"):
                        attrs = []
                        for item in node.body:
                            # AnnAssign matches variables with type annotations (e.g., m_sku: str)
                            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                                attrs.append(item.target.id)
                        if attrs:
                            matrix[node.name] = attrs
            except Exception as e:
                print(f"Warning: Failed to parse file {filename} cleanly: {e}")

    if not matrix:
        print("Error: No valid Canonical classes or attributes extracted.")
        return

    # 2. Extract and organize all distinct attribute names
    all_attrs = set()
    for attrs in matrix.values():
        all_attrs.update(attrs)

    # Establish custom sorting: core fields at the top, the rest alphabetical
    priority_attrs = ["m_sku", "m_brand", "m_name", "m_type", "datasheet_url", "img"]
    other_attrs = sorted(list(all_attrs - set(priority_attrs)))
    final_attr_list = [a for a in priority_attrs if a in all_attrs] + other_attrs

    # 3. Construct the Markdown table representation
    columns = sorted(list(matrix.keys()))
    headers = ["Attribute"] + columns
    
    markdown_lines = [
        "# Canonical Models Attribute Overlap Matrix\n",
        "This file is automatically generated by parsing model code layouts to show cross-component attribute maps.\n",
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |"
    ]
    
    for attr in final_attr_list:
        row = [f"`{attr}`"]
        for col in columns:
            if attr in matrix[col]:
                row.append("✅")
            else:
                row.append("❌")
        markdown_lines.append("| " + " | ".join(row) + " |")

    # 4. Save out to README.md inside the same directory
    output_filepath = os.path.join(models_dir, "README.md")
    try:
        with open(output_filepath, "w", encoding="utf-8") as out:
            out.write("\n".join(markdown_lines) + "\n")
        print(f"Success! Output matrix generated successfully inside: '{output_filepath}'")
    except IOError as e:
        print(f"Error writing out Markdown document: {e}")

if __name__ == "__main__":
    generate_matrix()